name: CI Pipeline
on:
  push:
    branches:
      - main
    tags:
      - '*'
  pull_request:
    branches:
      - '*'
  schedule:
    - cron: "15 7 * * *" # Nightly build at 7:15 AM (UDT)
  workflow_dispatch:  # This enables manual triggering

jobs:
  linux:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        platform: [linux-amd64]
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Check linux version
        run: uname -a
      - name: linux install dependencies
        run: |
          rustup update
      - name: linux build (rustc)
        run: |
          ./build
          ./bin/bmw || exit 1;
      - name: linux build (mrustc)
        run: |
          export CC=gcc
          mkdir ../famc
          cd ../famc
          wget https://github.com/cgilliard/famc/releases/download/0.0.1/famc_linux.tar.gz
          gzip -dc famc_linux.tar.gz | tar xvf -
          cd ../bitcoinmw
          ./build clean
          export MRUSTC=../famc/bin/mrustc
          export OUTPUT=../famc/output-1.29.0
          ./build mrustc || exit 1;
          ./bin/bmw || exit 1;
      - name: linux tests
        run: |
          ./build clean
          ./test
      - name: address sanitize
        run: |
          rustup default nightly
          ./build clean
          ./asan
      - name: code coverage
        run: |
          cargo install grcov --version 0.8.22
          rustup component add llvm-tools-preview
          git clone https://anything:${{ secrets.BitcoinMWPat }}@github.com/cgilliard/bitcoinmw.git _coverage
          cd _coverage
          git config user.name "Coverage-Bot"
          git config user.email "noreply@pipeline.com"
          git checkout main
          ./build clean
          ./coverage
          ./scripts/update_code_coverage.sh
          git commit -am "Coverage-Bot: Updated repo (via main.yml script) Source Version is $GITHUB_SHA";
          if [[ "$GITHUB_EVENT_NAME" == "schedule" || "$GITHUB_EVENT_NAME" == "workflow_dispatch" ]]; then
            git push https://${{ secrets.BitcoinMWPat }}@github.com/cgilliard/bitcoinmw.git
          fi
      - name: linux bootstrap (mrustc)
        run: |
          if [[ "$GITHUB_EVENT_NAME" == "schedule" || "$GITHUB_EVENT_NAME" == "workflow_dispatch" ]]; then
            git clone https://github.com/cgilliard/famc ../famc_src
            cd ../famc_src
            export CXX=g++
            export CC=gcc
            ./build.sh
            cd ../bitcoinmw
            ./build clean
            export MRUSTC=../famc_src/bin/mrustc
            export OUTPUT=../famc_src/output-1.29.0
            ./build mrustc || exit 1;
            ./bin/bmw || exit 1;
          fi
  macos:
    runs-on: macos-latest
    strategy:
      matrix:
        platform: [macos]
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Check macos version
        run: |
          sw_vers
      - name: macos install dependencies
        run: |
          rustup update
          brew install autoconf automake libtool
          sudo mkdir -p /usr/local/lib
          sudo cp `brew --prefix gmp`/lib/libgmp.a /usr/local/lib
      - name: macos build (rustc)
        run: |
          ./build
          ./bin/bmw || exit 1;
      - name: macos build (mrustc)
        run: |
          export LIBRARY_PATH="$(brew --prefix gmp)/lib:$LIBRARY_PATH"
          export CXX=clang++
          export CC=clang
          mkdir ../famc
          cd ../famc
          wget https://github.com/cgilliard/famc/releases/download/0.0.1/famc_macos.tar.gz
          gzip -dc famc_macos.tar.gz | tar xvf -
          cd ../bitcoinmw
          ./build clean
          export MRUSTC=../famc/bin/mrustc
          export OUTPUT=../famc/output-1.29.0
          ./build mrustc || exit 1;
          ./bin/bmw || exit 1;
      - name: macos tests
        run: |
          ./build clean
          ./test
      - name: macos bootstrap (mrustc)
        run: |
          if [[ "$GITHUB_EVENT_NAME" == "schedule" || "$GITHUB_EVENT_NAME" == "workflow_dispatch" ]]; then
            git clone https://github.com/cgilliard/famc ../famc_src
            cd ../famc_src
            export LIBRARY_PATH="$(brew --prefix gmp)/lib:$LIBRARY_PATH"
            export CXX=clang++
            export CC=clang
            ./build.sh
            cd ../bitcoinmw
            ./build clean
            export MRUSTC=../famc_src/bin/mrustc
            export OUTPUT=../famc_src/output-1.29.0
            ./build mrustc || exit 1;
            ./bin/bmw || exit 1;
          fi
