name: CI Pipeline
on:
  push:
    branches:
      - main
    tags:
      - '*'
  pull_request:
    branches:
      - '*'
  schedule:
    - cron: "15 7 * * *" # Nightly build at 7:15 AM (UDT)
  workflow_dispatch:  # This enables manual triggering

jobs:
  linux:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        platform: [linux-amd64]
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Check linux version
        run: uname -a
      - name: linux install dependencies
        run: |
          rustup update
      - name: linux build (rustc)
        run: |
          ./build
          ./bin/bmw || exit 1;
      - name: linux build (mrustc)
        run: |
          wget https://github.com/cgilliard/famc/releases/download/0.1.0/linux_output.tar.gz
          gzip -dc linux_output.tar.gz | tar xvf -
          ./build clean
          export CC=gcc
          export MRUSTC=./famc/bin/mrustc
          export OUTPUT=./famc/output
          ./build mrustc
          ./bin/bmw || exit 1;
      - name: linux tests
        run: |
          ./build clean
          ./test
      - name: code coverage
        run: |
          echo "code coverage"
      - name: linux bootstrap (mrustc)
        run: |
          if [[ "$GITHUB_EVENT_NAME" == "schedule" || "$GITHUB_EVENT_NAME" == "workflow_dispatch" ]]; then
            git clone https://github.com/cgilliard/famc famc_build
            cd famc_build
            ./build
            cd ..
            export CC=gcc
            export MRUSTC=./famc_build/bin/mrustc
            export OUTPUT=./famc_build/output
            ./build clean
            ./build mrustc
            ./bin/bmw || exit 1;
          fi
  macos:
    runs-on: macos-latest
    strategy:
      matrix:
        platform: [macos]
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Check macos version
        run: |
          sw_vers
      - name: macos install dependencies
        run: |
          rustup update
          brew install autoconf automake libtool
      - name: macos build (rustc)
        run: |
          ./build
          ./bin/bmw || exit 1;
      - name: macos build (mrustc)
        run: |
          export CXX=/opt/homebrew/bin/g++-13
          export CC=/opt/homebrew/bin/gcc-13
          wget https://github.com/cgilliard/famc/releases/download/0.1.0/macos_output.tar.gz
          gzip -dc macos_output.tar.gz | tar xvf -
          ./build clean
          export MRUSTC=./famc/bin/mrustc
          export OUTPUT=./famc/output
          ./build mrustc
          ./bin/bmw || exit 1;
      - name: macos tests
        run: |
          ./build clean
          ./test
      - name: macos bootstrap (mrustc)
        run: |
          if [[ "$GITHUB_EVENT_NAME" == "schedule" || "$GITHUB_EVENT_NAME" == "workflow_dispatch" ]]; then
            git clone https://github.com/cgilliard/famc famc_build
            cd famc_build
            export CXX=/opt/homebrew/bin/g++-13
            export CC=/opt/homebrew/bin/gcc-13
            ./build
            cd ..
            ./build clean
            export MRUSTC=./famc_build/bin/mrustc
            export OUTPUT=./famc_build/output
            ./build mrustc
            ./bin/bmw || exit 1;
          fi
